In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score)

In [36]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("Test.csv")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [37]:
print(df_train.head())
print("***************************************************")
print(df_train.info())
print("***************************************************")
print(df_train.describe())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003
1       Norm     1Fam     1Story            6            8       1976
2       Norm     1Fam     2Story            7            5       2001
3       Norm     1Fam     2Story            7            5       1915
4       Norm     1Fam     2Story            8            5       2000

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace
1          1976     Gable  CompShg     MetalSd     MetalSd        NaN
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace
3          1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No
1         0.0        TA        TA     CBlock       Gd       TA           Gd
2       162.0        Gd        TA      PConc       Gd       TA           Mn
3         0.0        TA        TA     BrkTil       TA       Gd           No
4       350.0        Gd        TA      PConc       Gd       TA           Av

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856
1          ALQ         978          Unf           0        284         1262
2          GLQ         486          Unf           0        434          920
3          ALQ         216          Unf           0        540          756
4          GLQ         655          Unf           0        490         1145

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0
1    GasA        Ex          Y      SBrkr      1262         0             0
2    GasA        Ex          Y      SBrkr       920       866             0
3    GasA        Gd          Y      SBrkr       961       756             0
4    GasA        Ex          Y      SBrkr      1145      1053             0

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3
1       1262             0             1         2         0             3
2       1786             1             0         2         1             3
3       1717             1             0         1         0             3
4       2198             1             0         2         1             4

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN
1             1          TA             6        Typ           1          TA
2             1          Gd             6        Typ           1          TA
3             1          Gd             7        Typ           1          Gd
4             1          Gd             9        Typ           1          TA

  GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual  \
0     Attchd       2003.0          RFn           2         548         TA
1     Attchd       1976.0          RFn           2         460         TA
2     Attchd       2001.0          RFn           2         608         TA
3     Detchd       1998.0          Unf           3         642         TA
4     Attchd       2000.0          RFn           3         836         TA

  GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0         TA          Y           0           61              0          0
1         TA          Y         298            0              0          0
2         TA          Y           0           42              0          0
3         TA          Y           0           35            272          0
4         TA          Y         192           84              0          0

   ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold  \
0            0         0    NaN   NaN         NaN        0       2    2008
1            0         0    NaN   NaN         NaN        0       5    2007
2            0         0    NaN   NaN         NaN        0       9    2008
3            0         0    NaN   NaN         NaN        0       2    2006
4            0         0    NaN   NaN         NaN        0      12    2008

  SaleType SaleCondition  SalePrice
0       WD        Normal     208500
1       WD        Normal     181500
2       WD        Normal     223500
3       WD       Abnorml     140000
4       WD        Normal     250000
***************************************************
<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB
None
***************************************************
                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000
mean    730.500000    56.897260    70.049958   10516.828082     6.099315
std     421.610009    42.300571    24.284752    9981.264932     1.382997
min       1.000000    20.000000    21.000000    1300.000000     1.000000
25%     365.750000    20.000000    59.000000    7553.500000     5.000000
50%     730.500000    50.000000    69.000000    9478.500000     6.000000
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000
max    1460.000000   190.000000   313.000000  215245.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726
std       1.112799    30.202904     20.645407   181.066207   456.098091
min       1.000000  1872.000000   1950.000000     0.000000     0.000000
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000

        BsmtFinSF2    BsmtUnfSF  TotalBsmtSF     1stFlrSF     2ndFlrSF  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000
mean     46.549315   567.240411  1057.429452  1162.626712   346.992466
std     161.319273   441.866955   438.705324   386.587738   436.528436
min       0.000000     0.000000     0.000000   334.000000     0.000000
25%       0.000000   223.000000   795.750000   882.000000     0.000000
50%       0.000000   477.500000   991.500000  1087.000000     0.000000
75%       0.000000   808.000000  1298.250000  1391.250000   728.000000
max    1474.000000  2336.000000  6110.000000  4692.000000  2065.000000

       LowQualFinSF    GrLivArea  BsmtFullBath  BsmtHalfBath     FullBath  \
count   1460.000000  1460.000000   1460.000000   1460.000000  1460.000000
mean       5.844521  1515.463699      0.425342      0.057534     1.565068
std       48.623081   525.480383      0.518911      0.238753     0.550916
min        0.000000   334.000000      0.000000      0.000000     0.000000
25%        0.000000  1129.500000      0.000000      0.000000     1.000000
50%        0.000000  1464.000000      0.000000      0.000000     2.000000
75%        0.000000  1776.750000      1.000000      0.000000     2.000000
max      572.000000  5642.000000      3.000000      2.000000     3.000000

          HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd   Fireplaces  \
count  1460.000000   1460.000000   1460.000000   1460.000000  1460.000000
mean      0.382877      2.866438      1.046575      6.517808     0.613014
std       0.502885      0.815778      0.220338      1.625393     0.644666
min       0.000000      0.000000      0.000000      2.000000     0.000000
25%       0.000000      2.000000      1.000000      5.000000     0.000000
50%       0.000000      3.000000      1.000000      6.000000     1.000000
75%       1.000000      3.000000      1.000000      7.000000     1.000000
max       2.000000      8.000000      3.000000     14.000000     3.000000

       GarageYrBlt   GarageCars   GarageArea   WoodDeckSF  OpenPorchSF  \
count  1379.000000  1460.000000  1460.000000  1460.000000  1460.000000
mean   1978.506164     1.767123   472.980137    94.244521    46.660274
std      24.689725     0.747315   213.804841   125.338794    66.256028
min    1900.000000     0.000000     0.000000     0.000000     0.000000
25%    1961.000000     1.000000   334.500000     0.000000     0.000000
50%    1980.000000     2.000000   480.000000     0.000000    25.000000
75%    2002.000000     2.000000   576.000000   168.000000    68.000000
max    2010.000000     4.000000  1418.000000   857.000000   547.000000

       EnclosedPorch    3SsnPorch  ScreenPorch     PoolArea       MiscVal  \
count    1460.000000  1460.000000  1460.000000  1460.000000   1460.000000
mean       21.954110     3.409589    15.060959     2.758904     43.489041
std        61.119149    29.317331    55.757415    40.177307    496.123024
min         0.000000     0.000000     0.000000     0.000000      0.000000
25%         0.000000     0.000000     0.000000     0.000000      0.000000
50%         0.000000     0.000000     0.000000     0.000000      0.000000
75%         0.000000     0.000000     0.000000     0.000000      0.000000
max       552.000000   508.000000   480.000000   738.000000  15500.000000

            MoSold       YrSold      SalePrice
count  1460.000000  1460.000000    1460.000000
mean      6.321918  2007.815753  180921.195890
std       2.703626     1.328095   79442.502883
min       1.000000  2006.000000   34900.000000
25%       5.000000  2007.000000  129975.000000
50%       6.000000  2008.000000  163000.000000
75%       8.000000  2009.000000  214000.000000
max      12.000000  2010.000000  755000.000000

In [38]:
print(df_test.head())
print("***************************************************")
print(df_test.info())
print("***************************************************")
print(df_test.describe())

     Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg
1  1462          20       RL         81.0    14267   Pave   NaN      IR1
2  1463          60       RL         74.0    13830   Pave   NaN      IR1
3  1464          60       RL         78.0     9978   Pave   NaN      IR1
4  1465         120       RL         43.0     5005   Pave   NaN      IR1

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl        NAmes      Feedr
1         Lvl    AllPub    Corner       Gtl        NAmes       Norm
2         Lvl    AllPub    Inside       Gtl      Gilbert       Norm
3         Lvl    AllPub    Inside       Gtl      Gilbert       Norm
4         HLS    AllPub    Inside       Gtl      StoneBr       Norm

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     1Story            5            6       1961
1       Norm     1Fam     1Story            6            6       1958
2       Norm     1Fam     2Story            5            5       1997
3       Norm     1Fam     2Story            6            6       1998
4       Norm   TwnhsE     1Story            8            5       1992

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          1961     Gable  CompShg     VinylSd     VinylSd        NaN
1          1958       Hip  CompShg     Wd Sdng     Wd Sdng    BrkFace
2          1998     Gable  CompShg     VinylSd     VinylSd        NaN
3          1998     Gable  CompShg     VinylSd     VinylSd    BrkFace
4          1992     Gable  CompShg     HdBoard     HdBoard        NaN

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0         0.0        TA        TA     CBlock       TA       TA           No
1       108.0        TA        TA     CBlock       TA       TA           No
2         0.0        TA        TA      PConc       Gd       TA           No
3        20.0        TA        TA      PConc       TA       TA           No
4         0.0        Gd        TA      PConc       Gd       TA           No

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          Rec       468.0          LwQ       144.0      270.0        882.0
1          ALQ       923.0          Unf         0.0      406.0       1329.0
2          GLQ       791.0          Unf         0.0      137.0        928.0
3          GLQ       602.0          Unf         0.0      324.0        926.0
4          ALQ       263.0          Unf         0.0     1017.0       1280.0

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        TA          Y      SBrkr       896         0             0
1    GasA        TA          Y      SBrkr      1329         0             0
2    GasA        Gd          Y      SBrkr       928       701             0
3    GasA        Ex          Y      SBrkr       926       678             0
4    GasA        Ex          Y      SBrkr      1280         0             0

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0        896           0.0           0.0         1         0             2
1       1329           0.0           0.0         1         1             3
2       1629           0.0           0.0         2         1             3
3       1604           0.0           0.0         2         1             3
4       1280           0.0           0.0         2         0             2

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          TA             5        Typ           0         NaN
1             1          Gd             6        Typ           0         NaN
2             1          TA             6        Typ           1          TA
3             1          Gd             7        Typ           1          Gd
4             1          Gd             5        Typ           0         NaN

  GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual  \
0     Attchd       1961.0          Unf         1.0       730.0         TA
1     Attchd       1958.0          Unf         1.0       312.0         TA
2     Attchd       1997.0          Fin         2.0       482.0         TA
3     Attchd       1998.0          Fin         2.0       470.0         TA
4     Attchd       1992.0          RFn         2.0       506.0         TA

  GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0         TA          Y         140            0              0          0
1         TA          Y         393           36              0          0
2         TA          Y         212           34              0          0
3         TA          Y         360           36              0          0
4         TA          Y           0           82              0          0

   ScreenPorch  PoolArea PoolQC  Fence MiscFeature  MiscVal  MoSold  YrSold  \
0          120         0    NaN  MnPrv         NaN        0       6    2010
1            0         0    NaN    NaN        Gar2    12500       6    2010
2            0         0    NaN  MnPrv         NaN        0       3    2010
3            0         0    NaN    NaN         NaN        0       6    2010
4          144         0    NaN    NaN         NaN        0       1    2010

  SaleType SaleCondition
0       WD        Normal
1       WD        Normal
2       WD        Normal
3       WD        Normal
4       WD        Normal
***************************************************
<class 'pandas.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   str
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   str
 6   Alley          107 non-null    str
 7   LotShape       1459 non-null   str
 8   LandContour    1459 non-null   str
 9   Utilities      1457 non-null   str
 10  LotConfig      1459 non-null   str
 11  LandSlope      1459 non-null   str
 12  Neighborhood   1459 non-null   str
 13  Condition1     1459 non-null   str
 14  Condition2     1459 non-null   str
 15  BldgType       1459 non-null   str
 16  HouseStyle     1459 non-null   str
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   str
 22  RoofMatl       1459 non-null   str
 23  Exterior1st    1458 non-null   str
 24  Exterior2nd    1458 non-null   str
 25  MasVnrType     565 non-null    str
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   str
 28  ExterCond      1459 non-null   str
 29  Foundation     1459 non-null   str
 30  BsmtQual       1415 non-null   str
 31  BsmtCond       1414 non-null   str
 32  BsmtExposure   1415 non-null   str
 33  BsmtFinType1   1417 non-null   str
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   str
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   str
 40  HeatingQC      1459 non-null   str
 41  CentralAir     1459 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   str
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   str
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    str
 58  GarageType     1383 non-null   str
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   str
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   str
 64  GarageCond     1381 non-null   str
 65  PavedDrive     1459 non-null   str
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      str
 73  Fence          290 non-null    str
 74  MiscFeature    51 non-null     str
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   str
 79  SaleCondition  1459 non-null   str
dtypes: float64(11), int64(26), str(43)
memory usage: 912.0 KB
None
***************************************************
                Id   MSSubClass  LotFrontage       LotArea  OverallQual  \
count  1459.000000  1459.000000  1232.000000   1459.000000  1459.000000
mean   2190.000000    57.378341    68.580357   9819.161069     6.078821
std     421.321334    42.746880    22.376841   4955.517327     1.436812
min    1461.000000    20.000000    21.000000   1470.000000     1.000000
25%    1825.500000    20.000000    58.000000   7391.000000     5.000000
50%    2190.000000    50.000000    67.000000   9399.000000     6.000000
75%    2554.500000    70.000000    80.000000  11517.500000     7.000000
max    2919.000000   190.000000   200.000000  56600.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1459.000000  1459.000000   1459.000000  1444.000000  1458.000000
mean      5.553804  1971.357779   1983.662783   100.709141   439.203704
std       1.113740    30.390071     21.130467   177.625900   455.268042
min       1.000000  1879.000000   1950.000000     0.000000     0.000000
25%       5.000000  1953.000000   1963.000000     0.000000     0.000000
50%       5.000000  1973.000000   1992.000000     0.000000   350.500000
75%       6.000000  2001.000000   2004.000000   164.000000   753.500000
max       9.000000  2010.000000   2010.000000  1290.000000  4010.000000

        BsmtFinSF2    BsmtUnfSF  TotalBsmtSF     1stFlrSF     2ndFlrSF  \
count  1458.000000  1458.000000  1458.000000  1459.000000  1459.000000
mean     52.619342   554.294925  1046.117970  1156.534613   325.967786
std     176.753926   437.260486   442.898624   398.165820   420.610226
min       0.000000     0.000000     0.000000   407.000000     0.000000
25%       0.000000   219.250000   784.000000   873.500000     0.000000
50%       0.000000   460.000000   988.000000  1079.000000     0.000000
75%       0.000000   797.750000  1305.000000  1382.500000   676.000000
max    1526.000000  2140.000000  5095.000000  5095.000000  1862.000000

       LowQualFinSF    GrLivArea  BsmtFullBath  BsmtHalfBath     FullBath  \
count   1459.000000  1459.000000   1457.000000   1457.000000  1459.000000
mean       3.543523  1486.045922      0.434454      0.065202     1.570939
std       44.043251   485.566099      0.530648      0.252468     0.555190
min        0.000000   407.000000      0.000000      0.000000     0.000000
25%        0.000000  1117.500000      0.000000      0.000000     1.000000
50%        0.000000  1432.000000      0.000000      0.000000     2.000000
75%        0.000000  1721.000000      1.000000      0.000000     2.000000
max     1064.000000  5095.000000      3.000000      2.000000     4.000000

          HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  Fireplaces  \
count  1459.000000   1459.000000   1459.000000   1459.000000  1459.00000
mean      0.377656      2.854010      1.042495      6.385195     0.58122
std       0.503017      0.829788      0.208472      1.508895     0.64742
min       0.000000      0.000000      0.000000      3.000000     0.00000
25%       0.000000      2.000000      1.000000      5.000000     0.00000
50%       0.000000      3.000000      1.000000      6.000000     0.00000
75%       1.000000      3.000000      1.000000      7.000000     1.00000
max       2.000000      6.000000      2.000000     15.000000     4.00000

       GarageYrBlt   GarageCars   GarageArea   WoodDeckSF  OpenPorchSF  \
count  1381.000000  1458.000000  1458.000000  1459.000000  1459.000000
mean   1977.721217     1.766118   472.768861    93.174777    48.313914
std      26.431175     0.775945   217.048611   127.744882    68.883364
min    1895.000000     0.000000     0.000000     0.000000     0.000000
25%    1959.000000     1.000000   318.000000     0.000000     0.000000
50%    1979.000000     2.000000   480.000000     0.000000    28.000000
75%    2002.000000     2.000000   576.000000   168.000000    72.000000
max    2207.000000     5.000000  1488.000000  1424.000000   742.000000

       EnclosedPorch    3SsnPorch  ScreenPorch     PoolArea       MiscVal  \
count    1459.000000  1459.000000  1459.000000  1459.000000   1459.000000
mean       24.243317     1.794380    17.064428     1.744345     58.167923
std        67.227765    20.207842    56.609763    30.491646    630.806978
min         0.000000     0.000000     0.000000     0.000000      0.000000
25%         0.000000     0.000000     0.000000     0.000000      0.000000
50%         0.000000     0.000000     0.000000     0.000000      0.000000
75%         0.000000     0.000000     0.000000     0.000000      0.000000
max      1012.000000   360.000000   576.000000   800.000000  17000.000000

            MoSold       YrSold
count  1459.000000  1459.000000
mean      6.104181  2007.769705
std       2.722432     1.301740
min       1.000000  2006.000000
25%       4.000000  2007.000000
50%       6.000000  2008.000000
75%       8.000000  2009.000000
max      12.000000  2010.000000

In [39]:
print("Is Null:")
fields_with_null_values = df_train.isnull().sum()
fields_with_null_values = fields_with_null_values[fields_with_null_values > 0]

null_info = pd.DataFrame({
    'Missing Values': fields_with_null_values,
    'Data Type': df_train.dtypes[fields_with_null_values.index]
})

print(null_info)

Is Null:
              Missing Values Data Type
LotFrontage              259   float64
Alley                   1369       str
MasVnrType               872       str
MasVnrArea                 8   float64
BsmtQual                  37       str
BsmtCond                  37       str
BsmtExposure              38       str
BsmtFinType1              37       str
BsmtFinType2              38       str
Electrical                 1       str
FireplaceQu              690       str
GarageType                81       str
GarageYrBlt               81   float64
GarageFinish              81       str
GarageQual                81       str
GarageCond                81       str
PoolQC                  1453       str
Fence                   1179       str
MiscFeature             1406       str

In [40]:
df_train[df_train["MasVnrArea"].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
234,235,60,RL,NaN,7851,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,2002,2002,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,625,Unf,0,235,860,GasA,Ex,Y,SBrkr,860,1100,0,1960,1,0,2,1,4,1,Gd,8,Typ,2,TA,BuiltIn,2002.0,Fin,2,440,TA,TA,Y,288,48,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,216500
529,530,20,RL,NaN,32668,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Crawfor,Norm,Norm,1Fam,1Story,6,3,1957,1975,Hip,CompShg,Wd Sdng,Stone,NaN,NaN,Gd,TA,PConc,TA,TA,No,Rec,1219,Unf,0,816,2035,GasA,TA,Y,SBrkr,2515,0,0,2515,1,0,3,0,4,2,TA,9,Maj1,2,TA,Attchd,1975.0,RFn,2,484,TA,TA,Y,0,0,200,0,0,0,NaN,NaN,NaN,0,3,2007,WD,Alloca,200624
650,651,60,FV,65.0,8125,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,2Story,7,6,2007,2007,Gable,CompShg,CemntBd,CmentBd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,Unf,0,Unf,0,813,813,GasA,Ex,Y,SBrkr,822,843,0,1665,0,0,2,1,3,1,Gd,7,Typ,0,NaN,Attchd,2007.0,RFn,2,562,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal,205950
936,937,20,RL,67.0,10083,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,1Fam,1Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,833,Unf,0,343,1176,GasA,Ex,Y,SBrkr,1200,0,0,1200,1,0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,2003.0,RFn,2,555,TA,TA,Y,0,41,0,0,0,0,NaN,NaN,NaN,0,8,2009,WD,Normal,184900
973,974,20,FV,95.0,11639,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Somerst,Norm,Norm,1Fam,1Story,7,5,2007,2008,Gable,CompShg,CemntBd,CmentBd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,Unf,0,Unf,0,1428,1428,GasA,Ex,Y,SBrkr,1428,0,0,1428,0,0,2,0,3,1,Gd,6,Typ,0,NaN,Attchd,2007.0,Fin,2,480,TA,TA,Y,0,120,0,0,0,0,NaN,NaN,NaN,0,12,2008,New,Partial,182000
977,978,120,FV,35.0,4274,Pave,Pave,IR1,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,TwnhsE,1Story,7,5,2006,2007,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,1106,Unf,0,135,1241,GasA,Ex,Y,SBrkr,1241,0,0,1241,1,0,1,1,1,1,Gd,4,Typ,0,NaN,Attchd,2007.0,Fin,2,569,TA,TA,Y,0,116,0,0,0,0,NaN,NaN,NaN,0,11,2007,New,Partial,199900
1243,1244,20,RL,107.0,13891,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,10,5,2006,2006,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Ex,TA,PConc,Ex,Gd,Gd,GLQ,1386,Unf,0,690,2076,GasA,Ex,Y,SBrkr,2076,0,0,2076,1,0,2,1,2,1,Ex,7,Typ,1,Gd,Attchd,2006.0,Fin,3,850,TA,TA,Y,216,229,0,0,0,0,NaN,NaN,NaN,0,9,2006,New,Partial,465000
1278,1279,60,RL,75.0,9473,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,8,5,2002,2002,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,804,Unf,0,324,1128,GasA,Ex,Y,SBrkr,1128,903,0,2031,1,0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,2002.0,RFn,2,577,TA,TA,Y,0,211,0,0,0,0,NaN,NaN,NaN,0,3,2008,WD,Normal,237000

In [41]:
df_train[df_train["Electrical"].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1379,1380,80,RL,73.0,9735,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Timber,Norm,Norm,1Fam,SLvl,5,5,2006,2007,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,384,384,GasA,Gd,Y,NaN,754,640,0,1394,0,0,2,1,3,1,Gd,7,Typ,0,NaN,BuiltIn,2007.0,Fin,2,400,TA,TA,Y,100,0,0,0,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500

In [42]:
df_train["LotFrontage"] = (
    df_train.groupby("Neighborhood")["LotFrontage"]
      .transform(lambda x: x.fillna(x.median()))
)

df_train["Electrical"] = df_train["Electrical"].fillna(
    df_train["Electrical"].mode()[0]
)

df_train["Alley"] = df_train["Alley"].fillna("None")
df_train["MasVnrType"] = df_train["MasVnrType"].fillna("None")
df_train["MasVnrArea"] = df_train["MasVnrArea"].fillna(0)
df_train["BsmtQual"] = df_train["BsmtQual"].fillna("None")
df_train["BsmtCond"] = df_train["BsmtCond"].fillna("None")
df_train["BsmtExposure"] = df_train["BsmtExposure"].fillna("None")
df_train["BsmtFinType1"] = df_train["BsmtFinType1"].fillna("None")
df_train["BsmtFinType2"] = df_train["BsmtFinType2"].fillna("None")
df_train["FireplaceQu"] = df_train["FireplaceQu"].fillna("None")
df_train["GarageType"] = df_train["GarageType"].fillna("None")
df_train["GarageYrBlt"] = df_train["GarageYrBlt"].fillna(0)
df_train["GarageFinish"] = df_train["GarageFinish"].fillna("None")
df_train["GarageQual"] = df_train["GarageQual"].fillna("None")
df_train["GarageCond"] = df_train["GarageCond"].fillna("None")
df_train["PoolQC"] = df_train["PoolQC"].fillna("None")
df_train["Fence"] = df_train["Fence"].fillna("None")
df_train["MiscFeature"] = df_train["MiscFeature"].fillna("None")

In [43]:
print("Is Null:")
fields_with_null_values = df_test.isnull().sum()
fields_with_null_values = fields_with_null_values[fields_with_null_values > 0]

null_info = pd.DataFrame({
    'Missing Values': fields_with_null_values,
    'Data Type': df_test.dtypes[fields_with_null_values.index]
})

print(null_info)

Is Null:
              Missing Values Data Type
MSZoning                   4       str
LotFrontage              227   float64
Alley                   1352       str
Utilities                  2       str
Exterior1st                1       str
Exterior2nd                1       str
MasVnrType               894       str
MasVnrArea                15   float64
BsmtQual                  44       str
BsmtCond                  45       str
BsmtExposure              44       str
BsmtFinType1              42       str
BsmtFinSF1                 1   float64
BsmtFinType2              42       str
BsmtFinSF2                 1   float64
BsmtUnfSF                  1   float64
TotalBsmtSF                1   float64
BsmtFullBath               2   float64
BsmtHalfBath               2   float64
KitchenQual                1       str
Functional                 2       str
FireplaceQu              730       str
GarageType                76       str
GarageYrBlt               78   float64
GarageFinish              78       str
GarageCars                 1   float64
GarageArea                 1   float64
GarageQual                78       str
GarageCond                78       str
PoolQC                  1456       str
Fence                   1169       str
MiscFeature             1408       str
SaleType                   1       str

In [44]:
df_test[df_test["MSZoning"].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
455,1916,30,NaN,109.0,21780,Grvl,NaN,Reg,Lvl,NaN,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,2,4,1910,1950,Gable,CompShg,Wd Sdng,Wd Sdng,NaN,0.0,Fa,Fa,CBlock,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,N,FuseA,810,0,0,810,0.0,0.0,1,0,1,1,TA,4,Min1,0,NaN,Detchd,1975.0,Unf,1.0,280.0,TA,TA,N,119,24,0,0,0,0,NaN,NaN,NaN,0,3,2009,ConLD,Normal
756,2217,20,NaN,80.0,14584,Pave,NaN,Reg,Low,AllPub,Inside,Mod,IDOTRR,Norm,Norm,1Fam,1Story,1,5,1952,1952,Gable,CompShg,AsbShng,VinylSd,NaN,0.0,Fa,Po,Slab,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,Wall,Po,N,FuseA,733,0,0,733,0.0,0.0,1,0,2,1,Fa,4,NaN,0,NaN,Attchd,1952.0,Unf,2.0,487.0,Fa,Po,N,0,0,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Abnorml
790,2251,70,NaN,NaN,56600,Pave,NaN,IR1,Low,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,2.5Unf,5,1,1900,1950,Hip,CompShg,Wd Sdng,Wd Sdng,NaN,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0.0,Unf,0.0,686.0,686.0,GasA,Ex,Y,SBrkr,1150,686,0,1836,0.0,0.0,2,0,4,1,TA,7,Maj1,0,NaN,Detchd,1900.0,Unf,1.0,288.0,TA,Fa,N,0,0,0,0,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal
1444,2905,20,NaN,125.0,31250,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Mitchel,Artery,Norm,1Fam,1Story,1,3,1951,1951,Gable,CompShg,CBlock,VinylSd,NaN,0.0,TA,Fa,CBlock,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,GasA,TA,Y,FuseA,1600,0,0,1600,0.0,0.0,1,1,3,1,TA,6,Mod,0,NaN,Attchd,1951.0,Unf,1.0,270.0,Fa,TA,N,0,0,135,0,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal

In [45]:
neighborhood_avg = [
  "LotFrontage"
]

str_category = [
  "MSZoning",
  "Utilities",
  "Exterior1st",
  "Exterior2nd",
  "SaleType"
]

na_to_none = [
  "Alley",
  "MasVnrType",
  "MasVnrArea",
  "BsmtQual",
  "BsmtCond",
  "BsmtExposure",
  "BsmtFinType1",
  "BsmtFinType2",
  "BsmtFullBath",
  "BsmtHalfBath",
  "KitchenQual",
  "Functional",
  "FireplaceQu",
  "GarageType",
  "GarageFinish",
  "GarageQual",
  "GarageCond",
  "PoolQC",
  "Fence",
  "MiscFeature"
]

na_to_0 = [
  "BsmtFinSF1",
  "BsmtFinSF2",
  "BsmtUnfSF",
  "TotalBsmtSF",
  "GarageYrBlt",
  "GarageCars",
  "GarageArea"
]

for item in neighborhood_avg:
  df_test[item] = (
    df_test.groupby("Neighborhood")[item]
    .transform(lambda x: x.fillna(x.median()))
  )

for item in str_category:
  df_test[item] = df_test[item].fillna(
      df_test[item].mode()[0]
  )

for item in na_to_none:
  df_test[item] = df_test[item].fillna("None")

for item in na_to_0:
  df_test[item] = df_test[item].fillna(0)

Nominal Catagories:
"MSSubClass",
"MSZoning",
"Street",
"Alley",
"LotShape",
"LandContour",
"Utilities",
"LotConfig",
"LandSlope",
"Neighborhood",
"Condition1",
"Condition2",
"BldgType",
"HouseStyle",
"RoofStyle",
"RoofMatl",
"Exterior1st",
"Exterior2nd",
"MasVnrType",
"Foundation",
"Heating",
"Electrical",
"GarageType",
"Fence",
"MiscFeature",
"SaleType",
"SaleCondition"

Y/N:
"CentralAir"

Ordinal 1-10:
"OverallQual",
"OverallCond"

Ordinal Po-Ex(5):
"ExterQual",
"ExterCond",
"HeatingQC",
"KitchenQual"

Ordinal Na-Ex(6):
"BsmtQual",
"BsmtCond",
"FireplaceQu",
"GarageQual",
"GarageCond"

Ordinal Na-Ex(5):
"PoolQC"

Ordinal Misc:
"BsmtExposure",
"BsmtFinType1",
"BsmtFinType2",
"Functional",
"GarageFinish",
"PavedDrive"??

In [46]:
# Nominal Map 
nominal_columns = [
"MSSubClass",
"MSZoning",
"Street",
"Alley",
"LotShape",
"LandContour",
"Utilities",
"LotConfig",
"LandSlope",
"Neighborhood",
"Condition1",
"Condition2",
"BldgType",
"HouseStyle",
"RoofStyle",
"RoofMatl",
"Exterior1st",
"Exterior2nd",
"MasVnrType",
"Foundation",
"Heating",
"Electrical",
"GarageType",
"Fence",
"MiscFeature",
"SaleType",
"SaleCondition"
]

df_train = pd.get_dummies(
  df_train,
  columns=nominal_columns,
drop_first=True
)

df_test = pd.get_dummies(
  df_test,
  columns=nominal_columns,
drop_first=True
)

datasets = [
  df_train,
  df_test
]

for dataset in datasets:
  #Ordinal Maps
  # Yes/No Map
  quality_map = {
    "N": 0,
    "Y": 1
  }

  dataset["CentralAir"] = dataset["CentralAir"].map(quality_map)

  # Poor - Excellent 5 Rankings Map
  quality_map = {
    "Po": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
  }

  ordinal_po_ex_5 = [
  "ExterQual",
  "ExterCond",
  "HeatingQC",
  "KitchenQual"
  ]

  for category in ordinal_po_ex_5:
    dataset[category]=dataset[category].map(quality_map)

  # NA - Excellent 6 Rankings Map
  quality_map = {
    "NA": 0,
    "None": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
  }

  ordinal_na_ex_6 = [
  "BsmtQual",
  "BsmtCond",
  "FireplaceQu",
  "GarageQual",
  "GarageCond"
  ]

  for category in ordinal_na_ex_6:
    dataset[category]=dataset[category].map(quality_map)

  # NA - Excellent 5 Rankings Map
  quality_map = {
    "NA": 0,
    "None": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
  }

  ordinal_na_ex_5 = [
    "PoolQC"
  ]

  for category in ordinal_na_ex_5:
    dataset[category]=dataset[category].map(quality_map)


  # Misc. Ordinal Rankings Map

  # "BsmtExposure"
  quality_map ={
    "NA": 0,
    "None": 0,
    "No":	1,
    "Mn":	2,
    "Av":	3,
    "Gd":	4
  }

  dataset["BsmtExposure"]=dataset["BsmtExposure"].map(quality_map)

  # "BsmtFinType1"
  # "BsmtFinType2"
  quality_map = {
    "NA": 0,
    "None": 0,
    "Unf": 1,
    "LwQ": 2,
    "Rec": 3,
    "BLQ": 4,
    "ALQ": 5,
    "GLQ": 6
  }

  dataset["BsmtFinType1"]=dataset["BsmtFinType1"].map(quality_map)
  dataset["BsmtFinType2"]=dataset["BsmtFinType2"].map(quality_map)

  # "Functional"
  quality_map ={
    "Sal": 0,
    "Sev": 1,
    "Maj2": 2,
    "Maj1": 3,
    "Mod": 4,
    "Min2": 5,
    "Min1": 6,
    "Typ": 7
  }
  dataset["Functional"]=dataset["Functional"].map(quality_map)

  # "GarageFinish"
  quality_map ={
    "NA": 0,
    "None": 0,
    "Unf": 1,
    "RFn": 2,
    "Fin": 3
  }

  dataset["GarageFinish"]=dataset["GarageFinish"].map(quality_map)


  # "PavedDrive"
  quality_map ={
    "N": 0,
    "P" : 1,
    "Y": 2
  }

  dataset["PavedDrive"]=dataset["PavedDrive"].map(quality_map)

In [47]:
print(df_train.head())
print("***************************************************")
print(df_train.info())
print("***************************************************")
print(df_train.describe())

   Id  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0   1         65.0     8450            7            5       2003
1   2         80.0     9600            6            8       1976
2   3         68.0    11250            7            5       2001
3   4         60.0     9550            7            5       1915
4   5         84.0    14260            8            5       2000

   YearRemodAdd  MasVnrArea  ExterQual  ExterCond  BsmtQual  BsmtCond  \
0          2003       196.0          3          2         4         3
1          1976         0.0          2          2         4         3
2          2002       162.0          3          2         4         3
3          1970         0.0          2          2         3         4
4          2000       350.0          3          2         4         3

   BsmtExposure  BsmtFinType1  BsmtFinSF1  BsmtFinType2  BsmtFinSF2  \
0             1             6         706             1           0
1             4             5         978             1           0
2             2             6         486             1           0
3             1             5         216             1           0
4             3             6         655             1           0

   BsmtUnfSF  TotalBsmtSF  HeatingQC  CentralAir  1stFlrSF  2ndFlrSF  \
0        150          856          4           1       856       854
1        284         1262          4           1      1262         0
2        434          920          4           1       920       866
3        540          756          3           1       961       756
4        490         1145          4           1      1145      1053

   LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  \
0             0       1710             1             0         2         1
1             0       1262             0             1         2         0
2             0       1786             1             0         2         1
3             0       1717             1             0         1         0
4             0       2198             1             0         2         1

   BedroomAbvGr  KitchenAbvGr  KitchenQual  TotRmsAbvGrd  Functional  \
0             3             1            3             8           7
1             3             1            2             6           7
2             3             1            3             6           7
3             3             1            3             7           7
4             4             1            3             9           7

   Fireplaces  FireplaceQu  GarageYrBlt  GarageFinish  GarageCars  GarageArea  \
0           0            0       2003.0             2           2         548
1           1            3       1976.0             2           2         460
2           1            3       2001.0             2           2         608
3           1            4       1998.0             1           3         642
4           1            3       2000.0             2           3         836

   GarageQual  GarageCond  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  \
0           3           3           2           0           61              0
1           3           3           2         298            0              0
2           3           3           2           0           42              0
3           3           3           2           0           35            272
4           3           3           2         192           84              0

   3SsnPorch  ScreenPorch  PoolArea  PoolQC  MiscVal  MoSold  YrSold  \
0          0            0         0       0        0       2    2008
1          0            0         0       0        0       5    2007
2          0            0         0       0        0       9    2008
3          0            0         0       0        0       2    2006
4          0            0         0       0        0      12    2008

   SalePrice  MSSubClass_30  MSSubClass_40  MSSubClass_45  MSSubClass_50  \
0     208500          False          False          False          False
1     181500          False          False          False          False
2     223500          False          False          False          False
3     140000          False          False          False          False
4     250000          False          False          False          False

   MSSubClass_60  MSSubClass_70  MSSubClass_75  MSSubClass_80  MSSubClass_85  \
0           True          False          False          False          False
1          False          False          False          False          False
2           True          False          False          False          False
3          False           True          False          False          False
4           True          False          False          False          False

   MSSubClass_90  MSSubClass_120  MSSubClass_160  MSSubClass_180  \
0          False           False           False           False
1          False           False           False           False
2          False           False           False           False
3          False           False           False           False
4          False           False           False           False

   MSSubClass_190  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0           False        False        False         True        False
1           False        False        False         True        False
2           False        False        False         True        False
3           False        False        False         True        False
4           False        False        False         True        False

   Street_Pave  Alley_None  Alley_Pave  LotShape_IR2  LotShape_IR3  \
0         True        True       False         False         False
1         True        True       False         False         False
2         True        True       False         False         False
3         True        True       False         False         False
4         True        True       False         False         False

   LotShape_Reg  LandContour_HLS  LandContour_Low  LandContour_Lvl  \
0          True            False            False             True
1          True            False            False             True
2         False            False            False             True
3         False            False            False             True
4         False            False            False             True

   Utilities_NoSeWa  LotConfig_CulDSac  LotConfig_FR2  LotConfig_FR3  \
0             False              False          False          False
1             False              False           True          False
2             False              False          False          False
3             False              False          False          False
4             False              False           True          False

   LotConfig_Inside  LandSlope_Mod  LandSlope_Sev  Neighborhood_Blueste  \
0              True          False          False                 False
1             False          False          False                 False
2              True          False          False                 False
3             False          False          False                 False
4             False          False          False                 False

   Neighborhood_BrDale  Neighborhood_BrkSide  Neighborhood_ClearCr  \
0                False                 False                 False
1                False                 False                 False
2                False                 False                 False
3                False                 False                 False
4                False                 False                 False

   Neighborhood_CollgCr  Neighborhood_Crawfor  Neighborhood_Edwards  \
0                  True                 False                 False
1                 False                 False                 False
2                  True                 False                 False
3                 False                  True                 False
4                 False                 False                 False

   Neighborhood_Gilbert  Neighborhood_IDOTRR  Neighborhood_MeadowV  \
0                 False                False                 False
1                 False                False                 False
2                 False                False                 False
3                 False                False                 False
4                 False                False                 False

   Neighborhood_Mitchel  Neighborhood_NAmes  Neighborhood_NPkVill  \
0                 False               False                 False
1                 False               False                 False
2                 False               False                 False
3                 False               False                 False
4                 False               False                 False

   Neighborhood_NWAmes  Neighborhood_NoRidge  Neighborhood_NridgHt  \
0                False                 False                 False
1                False                 False                 False
2                False                 False                 False
3                False                 False                 False
4                False                  True                 False

   Neighborhood_OldTown  Neighborhood_SWISU  Neighborhood_Sawyer  \
0                 False               False                False
1                 False               False                False
2                 False               False                False
3                 False               False                False
4                 False               False                False

   Neighborhood_SawyerW  Neighborhood_Somerst  Neighborhood_StoneBr  \
0                 False                 False                 False
1                 False                 False                 False
2                 False                 False                 False
3                 False                 False                 False
4                 False                 False                 False

   Neighborhood_Timber  Neighborhood_Veenker  Condition1_Feedr  \
0                False                 False             False
1                False                  True              True
2                False                 False             False
3                False                 False             False
4                False                 False             False

   Condition1_Norm  Condition1_PosA  Condition1_PosN  Condition1_RRAe  \
0             True            False            False            False
1            False            False            False            False
2             True            False            False            False
3             True            False            False            False
4             True            False            False            False

   Condition1_RRAn  Condition1_RRNe  Condition1_RRNn  Condition2_Feedr  \
0            False            False            False             False
1            False            False            False             False
2            False            False            False             False
3            False            False            False             False
4            False            False            False             False

   Condition2_Norm  Condition2_PosA  Condition2_PosN  Condition2_RRAe  \
0             True            False            False            False
1             True            False            False            False
2             True            False            False            False
3             True            False            False            False
4             True            False            False            False

   Condition2_RRAn  Condition2_RRNn  BldgType_2fmCon  BldgType_Duplex  \
0            False            False            False            False
1            False            False            False            False
2            False            False            False            False
3            False            False            False            False
4            False            False            False            False

   BldgType_Twnhs  BldgType_TwnhsE  HouseStyle_1.5Unf  HouseStyle_1Story  \
0           False            False              False              False
1           False            False              False               True
2           False            False              False              False
3           False            False              False              False
4           False            False              False              False

   HouseStyle_2.5Fin  HouseStyle_2.5Unf  HouseStyle_2Story  HouseStyle_SFoyer  \
0              False              False               True              False
1              False              False              False              False
2              False              False               True              False
3              False              False               True              False
4              False              False               True              False

   HouseStyle_SLvl  RoofStyle_Gable  RoofStyle_Gambrel  RoofStyle_Hip  \
0            False             True              False          False
1            False             True              False          False
2            False             True              False          False
3            False             True              False          False
4            False             True              False          False

   RoofStyle_Mansard  RoofStyle_Shed  RoofMatl_CompShg  RoofMatl_Membran  \
0              False           False              True             False
1              False           False              True             False
2              False           False              True             False
3              False           False              True             False
4              False           False              True             False

   RoofMatl_Metal  RoofMatl_Roll  RoofMatl_Tar&Grv  RoofMatl_WdShake  \
0           False          False             False             False
1           False          False             False             False
2           False          False             False             False
3           False          False             False             False
4           False          False             False             False

   RoofMatl_WdShngl  Exterior1st_AsphShn  Exterior1st_BrkComm  \
0             False                False                False
1             False                False                False
2             False                False                False
3             False                False                False
4             False                False                False

   Exterior1st_BrkFace  Exterior1st_CBlock  Exterior1st_CemntBd  \
0                False               False                False
1                False               False                False
2                False               False                False
3                False               False                False
4                False               False                False

   Exterior1st_HdBoard  Exterior1st_ImStucc  Exterior1st_MetalSd  \
0                False                False                False
1                False                False                 True
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior1st_Plywood  Exterior1st_Stone  Exterior1st_Stucco  \
0                False              False               False
1                False              False               False
2                False              False               False
3                False              False               False
4                False              False               False

   Exterior1st_VinylSd  Exterior1st_Wd Sdng  Exterior1st_WdShing  \
0                 True                False                False
1                False                False                False
2                 True                False                False
3                False                 True                False
4                 True                False                False

   Exterior2nd_AsphShn  Exterior2nd_Brk Cmn  Exterior2nd_BrkFace  \
0                False                False                False
1                False                False                False
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior2nd_CBlock  Exterior2nd_CmentBd  Exterior2nd_HdBoard  \
0               False                False                False
1               False                False                False
2               False                False                False
3               False                False                False
4               False                False                False

   Exterior2nd_ImStucc  Exterior2nd_MetalSd  Exterior2nd_Other  \
0                False                False              False
1                False                 True              False
2                False                False              False
3                False                False              False
4                False                False              False

   Exterior2nd_Plywood  Exterior2nd_Stone  Exterior2nd_Stucco  \
0                False              False               False
1                False              False               False
2                False              False               False
3                False              False               False
4                False              False               False

   Exterior2nd_VinylSd  Exterior2nd_Wd Sdng  Exterior2nd_Wd Shng  \
0                 True                False                False
1                False                False                False
2                 True                False                False
3                False                False                 True
4                 True                False                False

   MasVnrType_BrkFace  MasVnrType_None  MasVnrType_Stone  Foundation_CBlock  \
0                True            False             False              False
1               False             True             False               True
2                True            False             False              False
3               False             True             False              False
4                True            False             False              False

   Foundation_PConc  Foundation_Slab  Foundation_Stone  Foundation_Wood  \
0              True            False             False            False
1             False            False             False            False
2              True            False             False            False
3             False            False             False            False
4              True            False             False            False

   Heating_GasA  Heating_GasW  Heating_Grav  Heating_OthW  Heating_Wall  \
0          True         False         False         False         False
1          True         False         False         False         False
2          True         False         False         False         False
3          True         False         False         False         False
4          True         False         False         False         False

   Electrical_FuseF  Electrical_FuseP  Electrical_Mix  Electrical_SBrkr  \
0             False             False           False              True
1             False             False           False              True
2             False             False           False              True
3             False             False           False              True

In [48]:
print(df_test.head())
print("***************************************************")
print(df_test.info())
print("***************************************************")
print(df_test.describe())

     Id  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0  1461         80.0    11622            5            6       1961
1  1462         81.0    14267            6            6       1958
2  1463         74.0    13830            5            5       1997
3  1464         78.0     9978            6            6       1998
4  1465         43.0     5005            8            5       1992

   YearRemodAdd MasVnrArea  ExterQual  ExterCond  BsmtQual  BsmtCond  \
0          1961        0.0          2          2         3         3
1          1958      108.0          2          2         3         3
2          1998        0.0          2          2         4         3
3          1998       20.0          2          2         3         3
4          1992        0.0          3          2         4         3

   BsmtExposure  BsmtFinType1  BsmtFinSF1  BsmtFinType2  BsmtFinSF2  \
0             1             3       468.0             2       144.0
1             1             5       923.0             1         0.0
2             1             6       791.0             1         0.0
3             1             6       602.0             1         0.0
4             1             5       263.0             1         0.0

   BsmtUnfSF  TotalBsmtSF  HeatingQC  CentralAir  1stFlrSF  2ndFlrSF  \
0      270.0        882.0          2           1       896         0
1      406.0       1329.0          2           1      1329         0
2      137.0        928.0          3           1       928       701
3      324.0        926.0          4           1       926       678
4     1017.0       1280.0          4           1      1280         0

   LowQualFinSF  GrLivArea BsmtFullBath BsmtHalfBath  FullBath  HalfBath  \
0             0        896          0.0          0.0         1         0
1             0       1329          0.0          0.0         1         1
2             0       1629          0.0          0.0         2         1
3             0       1604          0.0          0.0         2         1
4             0       1280          0.0          0.0         2         0

   BedroomAbvGr  KitchenAbvGr  KitchenQual  TotRmsAbvGrd  Functional  \
0             2             1          2.0             5         7.0
1             3             1          3.0             6         7.0
2             3             1          2.0             6         7.0
3             3             1          3.0             7         7.0
4             2             1          3.0             5         7.0

   Fireplaces  FireplaceQu  GarageYrBlt  GarageFinish  GarageCars  GarageArea  \
0           0            0       1961.0             1         1.0       730.0
1           0            0       1958.0             1         1.0       312.0
2           1            3       1997.0             3         2.0       482.0
3           1            4       1998.0             3         2.0       470.0
4           0            0       1992.0             2         2.0       506.0

   GarageQual  GarageCond  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  \
0           3           3           2         140            0              0
1           3           3           2         393           36              0
2           3           3           2         212           34              0
3           3           3           2         360           36              0
4           3           3           2           0           82              0

   3SsnPorch  ScreenPorch  PoolArea  PoolQC  MiscVal  MoSold  YrSold  \
0          0          120         0       0        0       6    2010
1          0            0         0       0    12500       6    2010
2          0            0         0       0        0       3    2010
3          0            0         0       0        0       6    2010
4          0          144         0       0        0       1    2010

   MSSubClass_30  MSSubClass_40  MSSubClass_45  MSSubClass_50  MSSubClass_60  \
0          False          False          False          False          False
1          False          False          False          False          False
2          False          False          False          False           True
3          False          False          False          False           True
4          False          False          False          False          False

   MSSubClass_70  MSSubClass_75  MSSubClass_80  MSSubClass_85  MSSubClass_90  \
0          False          False          False          False          False
1          False          False          False          False          False
2          False          False          False          False          False
3          False          False          False          False          False
4          False          False          False          False          False

   MSSubClass_120  MSSubClass_150  MSSubClass_160  MSSubClass_180  \
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False
4            True           False           False           False

   MSSubClass_190  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0           False        False         True        False        False
1           False        False        False         True        False
2           False        False        False         True        False
3           False        False        False         True        False
4           False        False        False         True        False

   Street_Pave  Alley_None  Alley_Pave  LotShape_IR2  LotShape_IR3  \
0         True        True       False         False         False
1         True        True       False         False         False
2         True        True       False         False         False
3         True        True       False         False         False
4         True        True       False         False         False

   LotShape_Reg  LandContour_HLS  LandContour_Low  LandContour_Lvl  \
0          True            False            False             True
1         False            False            False             True
2         False            False            False             True
3         False            False            False             True
4         False             True            False            False

   LotConfig_CulDSac  LotConfig_FR2  LotConfig_FR3  LotConfig_Inside  \
0              False          False          False              True
1              False          False          False             False
2              False          False          False              True
3              False          False          False              True
4              False          False          False              True

   LandSlope_Mod  LandSlope_Sev  Neighborhood_Blueste  Neighborhood_BrDale  \
0          False          False                 False                False
1          False          False                 False                False
2          False          False                 False                False
3          False          False                 False                False
4          False          False                 False                False

   Neighborhood_BrkSide  Neighborhood_ClearCr  Neighborhood_CollgCr  \
0                 False                 False                 False
1                 False                 False                 False
2                 False                 False                 False
3                 False                 False                 False
4                 False                 False                 False

   Neighborhood_Crawfor  Neighborhood_Edwards  Neighborhood_Gilbert  \
0                 False                 False                 False
1                 False                 False                 False
2                 False                 False                  True
3                 False                 False                  True
4                 False                 False                 False

   Neighborhood_IDOTRR  Neighborhood_MeadowV  Neighborhood_Mitchel  \
0                False                 False                 False
1                False                 False                 False
2                False                 False                 False
3                False                 False                 False
4                False                 False                 False

   Neighborhood_NAmes  Neighborhood_NPkVill  Neighborhood_NWAmes  \
0                True                 False                False
1                True                 False                False
2               False                 False                False
3               False                 False                False
4               False                 False                False

   Neighborhood_NoRidge  Neighborhood_NridgHt  Neighborhood_OldTown  \
0                 False                 False                 False
1                 False                 False                 False
2                 False                 False                 False
3                 False                 False                 False
4                 False                 False                 False

   Neighborhood_SWISU  Neighborhood_Sawyer  Neighborhood_SawyerW  \
0               False                False                 False
1               False                False                 False
2               False                False                 False
3               False                False                 False
4               False                False                 False

   Neighborhood_Somerst  Neighborhood_StoneBr  Neighborhood_Timber  \
0                 False                 False                False
1                 False                 False                False
2                 False                 False                False
3                 False                 False                False
4                 False                  True                False

   Neighborhood_Veenker  Condition1_Feedr  Condition1_Norm  Condition1_PosA  \
0                 False              True            False            False
1                 False             False             True            False
2                 False             False             True            False
3                 False             False             True            False
4                 False             False             True            False

   Condition1_PosN  Condition1_RRAe  Condition1_RRAn  Condition1_RRNe  \
0            False            False            False            False
1            False            False            False            False
2            False            False            False            False
3            False            False            False            False
4            False            False            False            False

   Condition1_RRNn  Condition2_Feedr  Condition2_Norm  Condition2_PosA  \
0            False             False             True            False
1            False             False             True            False
2            False             False             True            False
3            False             False             True            False
4            False             False             True            False

   Condition2_PosN  BldgType_2fmCon  BldgType_Duplex  BldgType_Twnhs  \
0            False            False            False           False
1            False            False            False           False
2            False            False            False           False
3            False            False            False           False
4            False            False            False           False

   BldgType_TwnhsE  HouseStyle_1.5Unf  HouseStyle_1Story  HouseStyle_2.5Unf  \
0            False              False               True              False
1            False              False               True              False
2            False              False              False              False
3            False              False              False              False
4             True              False               True              False

   HouseStyle_2Story  HouseStyle_SFoyer  HouseStyle_SLvl  RoofStyle_Gable  \
0              False              False            False             True
1              False              False            False            False
2               True              False            False             True
3               True              False            False             True
4              False              False            False             True

   RoofStyle_Gambrel  RoofStyle_Hip  RoofStyle_Mansard  RoofStyle_Shed  \
0              False          False              False           False
1              False           True              False           False
2              False          False              False           False
3              False          False              False           False
4              False          False              False           False

   RoofMatl_Tar&Grv  RoofMatl_WdShake  RoofMatl_WdShngl  Exterior1st_AsphShn  \
0             False             False             False                False
1             False             False             False                False
2             False             False             False                False
3             False             False             False                False
4             False             False             False                False

   Exterior1st_BrkComm  Exterior1st_BrkFace  Exterior1st_CBlock  \
0                False                False               False
1                False                False               False
2                False                False               False
3                False                False               False
4                False                False               False

   Exterior1st_CemntBd  Exterior1st_HdBoard  Exterior1st_MetalSd  \
0                False                False                False
1                False                False                False
2                False                False                False
3                False                False                False
4                False                 True                False

   Exterior1st_Plywood  Exterior1st_Stucco  Exterior1st_VinylSd  \
0                False               False                 True
1                False               False                False
2                False               False                 True
3                False               False                 True
4                False               False                False

   Exterior1st_Wd Sdng  Exterior1st_WdShing  Exterior2nd_AsphShn  \
0                False                False                False
1                 True                False                False
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior2nd_Brk Cmn  Exterior2nd_BrkFace  Exterior2nd_CBlock  \
0                False                False               False
1                False                False               False
2                False                False               False
3                False                False               False
4                False                False               False

   Exterior2nd_CmentBd  Exterior2nd_HdBoard  Exterior2nd_ImStucc  \
0                False                False                False
1                False                False                False
2                False                False                False
3                False                False                False
4                False                 True                False

   Exterior2nd_MetalSd  Exterior2nd_Plywood  Exterior2nd_Stone  \
0                False                False              False
1                False                False              False
2                False                False              False
3                False                False              False
4                False                False              False

   Exterior2nd_Stucco  Exterior2nd_VinylSd  Exterior2nd_Wd Sdng  \
0               False                 True                False
1               False                False                 True
2               False                 True                False
3               False                 True                False
4               False                False                False

   Exterior2nd_Wd Shng  MasVnrType_BrkFace  MasVnrType_None  MasVnrType_Stone  \
0                False               False             True             False
1                False                True            False             False
2                False               False             True             False
3                False                True            False             False
4                False               False             True             False

   Foundation_CBlock  Foundation_PConc  Foundation_Slab  Foundation_Stone  \
0               True             False            False             False
1               True             False            False             False
2              False              True            False             False
3              False              True            False             False
4              False              True            False             False

   Foundation_Wood  Heating_GasW  Heating_Grav  Heating_Wall  \
0            False         False         False         False
1            False         False         False         False
2            False         False         False         False
3            False         False         False         False
4            False         False         False         False

   Electrical_FuseF  Electrical_FuseP  Electrical_SBrkr  GarageType_Attchd  \
0             False             False              True               True
1             False             False              True               True
2             False             False              True               True
3             False             False              True               True
4             False             False              True               True

   GarageType_Basment  GarageType_BuiltIn  GarageType_CarPort  \
0               False               False               False
1               False               False               False
2               False               False               False
3               False               False               False
4               False               False               False

   GarageType_Detchd  GarageType_None  Fence_GdWo  Fence_MnPrv  Fence_MnWw  \
0              False            False       False         True       False
1              False            False       False        False       False
2              False            False       False         True       False
3              False            False       False        False       False
4              False            False       False        False       False

   Fence_None  MiscFeature_None  MiscFeature_Othr  MiscFeature_Shed  \
0       False              True             False             False
1        True             False             False             False
2       False              True             False             False
3        True              True             False             False
4        True              True             False             False

   SaleType_CWD  SaleType_Con  SaleType_ConLD  SaleType_ConLI  SaleType_ConLw  \
0         False         False           False           False           False

In [49]:
classification_df_train = df_train.copy()

classification_df_train["PriceCategory"] = pd.qcut(
    classification_df_train["SalePrice"],
    q=3,
    labels=["Low", "Medium", "High"]
)

classification_df_train.drop(
    columns=["SalePrice"],
    inplace=True
)



classification_df_train["PriceCategory"].value_counts()

PriceCategory
Medium    490
Low       487
High      483
Name: count, dtype: int64

In [52]:
y = df_train["SalePrice"]
x = df_train.drop(columns=["SalePrice"])
# y_classification = classification_df_train["PriceCategory"]
# x_classification = classification_df_train.drop(columns=["PriceCategory"])

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)


# x_train_classification, x_test_classification, y_train_classification, y_test_classification = train_test_split(
#     x_classification,
#     y_classification,
#     test_size=0.2,
#     random_state=42,
#     stratify=y_classification
# )

model = LinearRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

y_pred

array([160048.75723016, 332195.41412834, 105256.86037803, 194715.60029343,
       302763.52997436,  78224.94761931, 247863.49940402, 141767.86369062,
        77313.06242948, 145860.10835474, 145573.98628295, 102510.96089521,
        44539.02665361, 247445.44645228, 162279.50943577, 136571.31703096,
       192466.5282189 , 114670.72196834, 133217.40874107, 219830.95024843,
       143419.62281494, 203047.42835756, 181901.77348941, 127020.08528432,
       209922.50194625, 135527.05402636, 207806.34469645,  90911.30400868,
       157495.88525914, 184359.07675145, 126827.69101987, 299980.14655478,
       239856.07653086, 109137.49294634, 247633.86220045, 136605.04324336,
       143095.55107581, 210199.7473036 , 315172.7089539 ,  94125.79064552,
       144254.98580348, 238739.88488082,  93948.93409084, 332251.76845466,
       129813.45562829, 129397.14340864,  99358.03836491, 138209.83040997,
       390870.72727374, 130454.64052095, 118423.8737685 , 287468.51407042,
        99627.92530192, 292093.36645358, 149134.87700527, 238241.09356846,
       205692.67129594, 172687.67658941, 133847.43245435,  89237.04046547,
        54476.2053507 , 165802.84994367, 330787.34371169, 247731.45012322,
       295581.35449488, 199159.50614537,  98456.70064729, 300335.47897471,
       138619.54972909, 189780.73989439, 123894.20436106, 113422.28564795,
       101853.68727917,  39199.23427058, 438978.0636216 , 179177.35495351,
       305243.94005354, 412543.39973225, 147758.9977398 , 120310.72103075,
       116067.67977364,  50826.44622132, 123782.035592  ,  79856.25997333,
       157762.84659887, 134607.96509172, 260099.25396596, 204231.60692388,
       132534.60198189, 197243.20671819, 136017.95404682, 178568.86548861,
       196889.53776363, 254707.30334571, 124392.70524314, 199651.55421594,
       188472.84364308, 158640.11318393, 209435.01353262, 270054.78487409,
       151590.96186724, 213350.20550976, 284914.08133118, 139262.23698546,
       183879.56093997, 198926.61972821, 157791.64018349, 291508.17099846,
       153719.07836653, 203566.38859066,  33495.30393267, 146595.12556085,
       141534.86549541, 135645.69687226, 208104.1275665 , 134817.77079218,
        84684.07072762, 124953.3512464 , 100842.01831702, 297754.4434856 ,
       101315.0077847 , 135938.76304407, 185576.74226044, 187686.96113286,
       192810.98962085, 137818.20224526, 234495.29422101,  83755.85211173,
       140562.22960212, 192641.97947151, 189826.51835029, 320378.45122585,
       197127.17901706, 144676.3265494 ,  25723.04386997, 367912.89855136,
       340991.92323834, 157407.92399492, 231560.02011196, 532916.48773616,
       328634.68747033, 129753.5433533 , 179831.40735954, 145824.81801184,
       135860.69172637, 104690.23802186, 242660.61163082, 196887.98474094,
       133767.97530482,  50507.27925169, 100727.18162161, 139876.09806765,
       245755.90603877, 160751.57949221,  84257.74565681, 125721.78111142,
       149442.00856223, 151787.38505757,  95023.81948358, 128439.38699505,
       210357.964311  ,  97445.60940788, 302655.82072976, 157032.49085613,
       105278.58522992, 124489.854027  , 292782.72885473, 312338.61931149,
       417228.71976111, 224303.88724887, 359635.55244136,  93086.03711647,
       127590.32256103, 136365.52390303, 315688.81003215,  84442.23535307,
       149396.32320013, 230692.57552061, 134282.7204117 , 150668.89643321,
       190733.39796648,  89538.61767785, 124660.49063471, 150332.32285483,
       237768.94876183, 150589.4424033 , 279046.41868512, 225919.61205794,
       213712.73132206,  53141.10359146, 124008.95026689,  91731.04500395,
       162858.63422469, 134259.0825359 , 214901.77248254, 175999.4452424 ,
       194815.51062148,  64300.49719117, 210108.12297694, 123281.81344648,
       276295.38005712, 212648.24491148, 132978.57645263, 318720.0309268 ,
       202935.97687246, 114921.33832978, 228868.35859669, 129905.47861981,
       121401.61959961,  91499.43622545, 224935.30111079, 156847.07059113,
       122895.89993662, 177373.56188692, 214219.17170525, 248744.99837819,
       210397.25431276, 120957.559664  , 187700.87337108,  78173.05684288,
       142335.47954329, 235654.69432772, 210845.93470988,  85893.99632104,
       248711.59595062, 146963.01162687,  65059.07292451,  76391.37100425,
       149019.57248077,  88785.52887436,  82016.18433493, 166008.6324026 ,
       115371.07547032, 123179.82634946, 238516.99499644, 152721.22416373,
       207352.54357642, 154806.43935276, 245053.96295024, 100282.94165827,
       111799.16392829, 239974.59515166, 239470.66704184, 482306.74582422,
       196960.39053669, 135818.58253141,  77173.12857913, 179928.61903329,
       132168.06563954, 126183.63175387, 160283.52303403, 178947.06103739,
       148382.91868086,  77421.08268403, 145446.26251141, 144509.72042371,
        93659.61704611, 131667.19748589, 181767.69596231, 243803.9561157 ,
       325891.56685999, 199280.88803161, 124792.90306744, 245817.56199301,
       322721.87746519, 229129.95456761, 149567.21523231, 132750.9781743 ,
        90498.42923363, 194405.61134104, 379450.13965458, 249843.24949643,
       232735.99591502,  69199.58234836,  99842.47901696, 131693.33693675,
       121065.91116005, 279793.78923431, 231920.84338267, 129377.65378116,
       193079.30684489, 103749.88945177, 201538.1566013 , 103806.16552282,
       283194.28998746, 186421.24652576, 208348.74393687, 112333.52636722,
       292862.52994657, 200143.73298232, 101697.51698769, 113519.71226359])